In [2]:
import numpy as np

In [3]:
sequence_array = np.arange(10)

In [4]:
print(sequence_array, sequence_array.shape, sequence_array.dtype)

[0 1 2 3 4 5 6 7 8 9] (10,) int64


In [5]:
zero_array = np.zeros((3, 2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [6]:
one_array = np.ones((3, 2), dtype='int')

In [7]:
print(one_array)

[[1 1]
 [1 1]
 [1 1]]


In [8]:
one_array2 = one_array.reshape(2, 3)

In [9]:
print(one_array2)

[[1 1 1]
 [1 1 1]]


In [10]:
array1 = np.arange(10)

# reshape
- ndarray를 특정 차원 및 크기로 변환하는 메서드
- 변환을 원하는 크기를 함수 인자로 부여
- reshape(-1, 5)의 경우 고정된 5개의 컬럼에 맞게 로우 개수를 자동우로 새롭게 생성해 변환함

In [11]:
array2 = array1.reshape(-1, 5)
array3 = array2.reshape(-1, 2)

In [12]:
print('array2 : \n', array2)
print('array3 : \n', array3)

array2 : 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3 : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [13]:
array1 = np.arange(1, 9)
print('array1 :', array1)

value = array1[2]
print('value :', value)
print(type(value))

array1 : [1 2 3 4 5 6 7 8]
value : 3
<class 'numpy.int64'>


In [15]:
print(array1[array1>3])

[4 5 6 7 8]


In [23]:
array2 = array1.reshape(1, -1)

In [29]:
print(array2[0, 1])

2


In [35]:
array2 = np.arange(1, 10).reshape(3, 3)

In [37]:
array2[[0, 2], 1]

array([2, 8])

In [38]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# 불린 인덱싱
- 조건필터링과 검색을 동시에 할 수있음
- 인덱스를 지정하는 [] 내에 조건문을 그대로 기재하면 됨
- 혹은 동일한 불린 ndarray를 만들고 이를 [] 내에 인덱스로 입력하면 동일한 데이터 셋 변환

In [ ]:
print(array1[array1>3])

In [51]:
bool_indexes = np.array([True, False, False, False, False, False, False, True])

In [52]:
print(array1[bool_indexes])

[1 8]


In [48]:
print(array1)

[1 2 3 4 5 6 7 8]


# sort(), argsort()
## sort()
- 행렬의 정렬
- 내림차순으로 정렬하고자하면 메서드 뒤에 [::-1]을 붙이면 됨

## argsort()
- 정렬 행렬의 원본 행렬 인덱스를 ndarray 형으로 반환
- 내림차순으로 정렬하고자하면 메서드 뒤에 [::-1]을 붙이면 됨
- ndarray는 RDBS의 테이블 칼럼이나 판다스의 데이터 프레임 칼럼과 같은 메타 데이터를 가질 수 없음
    - 실제값과 그 값을 뜻하는 메타데이터를 별도의 ndarray로 각각 가져야만 함

In [53]:
test_array1 = np.array([3, 1, 9, 5])

In [57]:
sorted_array1 = np.sort(test_array1)[::-1]

In [58]:
sorted_array1

array([9, 5, 3, 1])

In [60]:
np.argsort(test_array1)[::-1]

array([2, 3, 0, 1])

In [65]:
name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)

print('성적 오름차순 정렬 시 score_array의 인덱스 :', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력 :', name_array[sort_indices_asc])
print(score_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스 : [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력 : ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']
[78 84 88 95 98]


# 행렬 내적(행렬 곱)
- 왼쪽 행렬의 로우(행)와 오른쪽 행렬의 칼럼(열)의 원소들을 순차적으로 곱한 뒤 그 결과를 모두 더한 값

In [68]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

dot_product = np.dot(A, B)
print('행렬 내적 결과 :\n', dot_product)

행렬 내적 결과 :
 [[ 58  64]
 [139 154]]


# 전치행렬
tranpose()

In [69]:
print(A)

print(np.transpose(A))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
