In [1]:
import numpy as np

In [2]:
sequence_array = np.arange(10)

In [4]:
print(sequence_array, sequence_array.shape, sequence_array.dtype)

[0 1 2 3 4 5 6 7 8 9] (10,) int64


In [5]:
zero_array = np.zeros((3, 2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [9]:
one_array = np.ones((3, 2), dtype='int')

In [10]:
print(one_array)

[[1 1]
 [1 1]
 [1 1]]


In [13]:
one_array2 = one_array.reshape(2, 3)

In [15]:
print(one_array2)

[[1 1 1]
 [1 1 1]]


In [20]:
array1 = np.arange(10)

# reshape
- ndarray를 특정 차원 및 크기로 변환하는 메서드
- 변환을 원하는 크기를 함수 인자로 부여
- reshape(-1, 5)의 경우 고정된 5개의 컬럼에 맞게 로우 개수를 자동우로 새롭게 생성해 변환함

In [18]:
array2 = array1.reshape(-1, 5)
array3 = array2.reshape(-1, 2)

In [19]:
print('array2 : \n', array2)
print('array3 : \n', array3)

array2 : 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3 : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [21]:
array1 = np.arange(1, 9)
print('array1 :', array1)

value = array1[2]
print('value :', value)
print(type(value))

array1 : [1 2 3 4 5 6 7 8]
value 3
<class 'numpy.int64'>
