In [1]:
import numpy as np

In [2]:
sequence_array = np.arange(10)

In [3]:
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [8]:
np.ones((3, 2), dtype='int32')

array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int32)

In [11]:
array1 = np.arange(10)
print(array1)

print(array1.reshape(-1, 5))
print(array1.reshape(-1))

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]


In [14]:
array1 = np.arange(8)
print(array1.reshape(2, 2, 2))

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [17]:
array1[-1]

7

In [18]:
array1[0] = 9
print(array1)

[9 1 2 3 4 5 6 7]


In [20]:
array1 = np.arange(1, 10)

array1 = array1.reshape(3, 3)
print(array1)
print()
print(array1[1, 1])
print(array1[1, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

5
6


In [21]:
array1.tolist()

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [22]:
array1 = np.arange(1, 10)
array3 = array1[array1 > 5]
print(array3)

[6 7 8 9]


In [23]:
array1 > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [26]:
array1[np.array([1, 3, 5, 7])]

array([2, 4, 6, 8])

In [28]:
array1 = np.array([3, 1, 9, 5])

In [30]:
np.sort(array1)[::-1]

array([9, 5, 3, 1])

In [33]:
array1 = np.array([[8, 12],
                   [7, 1]])

np.sort(array1, axis=1)

array([[ 8, 12],
       [ 1,  7]])

In [36]:
array1 = np.array([3, 1, 9, 5])
sort_indices = np.argmax(array1)
print(sort_indices)
print(array1[sort_indices])

2
9


In [39]:
import pandas as pd

titanic_df = pd.read_csv('../data/titanic/train.csv')
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [43]:
titanic_df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [44]:
print(titanic_df['Pclass'].value_counts())

3    491
1    216
2    184
Name: Pclass, dtype: int64


In [45]:
titanic_df['Pclass'].head()

0    3
1    1
2    3
3    1
4    3
Name: Pclass, dtype: int64

In [46]:
titanic_df['Embarked'].value_counts(dropna=False)

S      644
C      168
Q       77
NaN      2
Name: Embarked, dtype: int64

In [50]:
dict1 = {'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33] }
df_dict = pd.DataFrame(dict1)

In [60]:
array3 = df_dict.values
array3.tolist()


[[1, 2, 3], [11, 22, 33]]

In [62]:
df_dict.to_dict('list')

{'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}

In [64]:
titanic_df.index = np.arange(1, 892)

In [65]:
titanic_df

PassengerId  Survived  Pclass  \
1              1         0       3   
2              2         1       1   
3              3         1       3   
4              4         1       1   
5              5         0       3   
..           ...       ...     ...   
887          887         0       2   
888          888         1       1   
889          889         0       3   
890          890         1       1   
891          891         0       3   

                                                  Name     Sex   Age  SibSp  \
1                              Braund, Mr. Owen Harris    male  22.0      1   
2    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3                               Heikkinen, Miss. Laina  female  26.0      0   
4         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
5                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
887                              Montvila, Rev. Juozas    male  27.0      0   
888                       Graham, Miss. Margaret Edith  female  19.0      0   
889           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
890                              Behr, Mr. Karl Howell    male  26.0      0   
891                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
1        0         A/5 21171   7.2500   NaN        S  
2        0          PC 17599  71.2833   C85        C  
3        0  STON/O2. 3101282   7.9250   NaN        S  
4        0            113803  53.1000  C123        S  
5        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
887      0            211536  13.0000   NaN        S  
888      0            112053  30.0000   B42        S  
889      2        W./C. 6607  23.4500   NaN        S  
890      0            111369  30.0000  C148        C  
891      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [68]:
titanic_df.reset_index(drop=True)

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [72]:
titanic_df['Pclass'].value_counts().reset_index(name='class',)

index  class
0      3    491
1      1    216
2      2    184

In [74]:
boolean = titanic_df['Age']>60
type(boolean)

pandas.core.series.Series

In [77]:
titanic_df[titanic_df['Age']>60][['Name', 'Age']].head()

Name   Age
34            Wheadon, Mr. Edward H  66.0
55   Ostby, Mr. Engelhart Cornelius  65.0
97        Goldschmidt, Mr. George B  71.0
117            Connors, Mr. Patrick  70.5
171       Van der hoef, Mr. Wyckoff  61.0

In [78]:
titanic_df[['Age', 'Fare']].mean()

Age     29.699118
Fare    32.204208
dtype: float64

In [88]:
agg_format = {'Age':'max', 'SibSp':'sum'}
titanic_df.groupby('Pclass').agg(agg_format)

Age  SibSp
Pclass             
1       80.0     90
2       70.0     74
3       74.0    302

In [89]:
titanic_df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [91]:
titanic_df['Cabin'] = titanic_df['Cabin'].fillna('C000')
titanic_df.head()

PassengerId  Survived  Pclass  \
1            1         0       3   
2            2         1       1   
3            3         1       3   
4            4         1       1   
5            5         0       3   

                                                Name     Sex   Age  SibSp  \
1                            Braund, Mr. Owen Harris    male  22.0      1   
2  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3                             Heikkinen, Miss. Laina  female  26.0      0   
4       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
5                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
1      0         A/5 21171   7.2500  C000        S  
2      0          PC 17599  71.2833   C85        C  
3      0  STON/O2. 3101282   7.9250  C000        S  
4      0            113803  53.1000  C123        S  
5      0            373450   8.0500  C000        S

In [92]:
titanic_df['Age'] = titanic_df['Age'].fillna(titanic_df['Age'].mean())
titanic_df['Embarked'] = titanic_df['Embarked'].fillna('S')
titanic_df.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [95]:
a = [1, 2, 3]
list(map(lambda x : x**2, a))

[1, 4, 9]

In [98]:
titanic_df['Name_len'] = titanic_df['Name'].apply(lambda x : len(x))
titanic_df.head()

PassengerId  Survived  Pclass  \
1            1         0       3   
2            2         1       1   
3            3         1       3   
4            4         1       1   
5            5         0       3   

                                                Name     Sex   Age  SibSp  \
1                            Braund, Mr. Owen Harris    male  22.0      1   
2  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3                             Heikkinen, Miss. Laina  female  26.0      0   
4       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
5                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  Name_len  
1      0         A/5 21171   7.2500  C000        S        23  
2      0          PC 17599  71.2833   C85        C        51  
3      0  STON/O2. 3101282   7.9250  C000        S        22  
4      0            113803  53.1000  C123        S        44  
5      0            373450   8.0500  C000        S        24

In [100]:
titanic_df['Child_Adult'] = titanic_df['Age'].apply(lambda x : 'Child' if x < 15 else 'Adult')
titanic_df.head()

PassengerId  Survived  Pclass  \
1            1         0       3   
2            2         1       1   
3            3         1       3   
4            4         1       1   
5            5         0       3   

                                                Name     Sex   Age  SibSp  \
1                            Braund, Mr. Owen Harris    male  22.0      1   
2  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3                             Heikkinen, Miss. Laina  female  26.0      0   
4       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
5                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  Name_len Child_Adult  
1      0         A/5 21171   7.2500  C000        S        23       Adult  
2      0          PC 17599  71.2833   C85        C        51       Adult  
3      0  STON/O2. 3101282   7.9250  C000        S        22       Adult  
4      0            113803  53.1000  C123        S        44       Adult  
5      0            373450   8.0500  C000        S        24       Adult

In [102]:
titanic_df['Child_Adult'].value_counts()

Adult    813
Child     78
Name: Child_Adult, dtype: int64

In [103]:
titanic_df['Child_Adult'] = titanic_df['Age'].apply(lambda x : 'Child' if x <= 15 else ('Adult' if x <= 60 else 'Elderly'))

In [105]:
titanic_df['Child_Adult'].value_counts()

Adult      786
Child       83
Elderly     22
Name: Child_Adult, dtype: int64

In [106]:
def get_category(age):
    cat = ''
    if age < 15:
        cat = 'Child'
    elif age < 25:
        cat = 'Young'
    elif age < 40:
        cat = 'Adult'
    elif age < 60:
        cat = 'Parent'
    else:
        cat = 'Elderly'
    return cat

titanic_df['Child_Adult'] = titanic_df['Age'].apply(get_category)




In [107]:
titanic_df.head(20)

PassengerId  Survived  Pclass  \
1             1         0       3   
2             2         1       1   
3             3         1       3   
4             4         1       1   
5             5         0       3   
6             6         0       3   
7             7         0       1   
8             8         0       3   
9             9         1       3   
10           10         1       2   
11           11         1       3   
12           12         1       1   
13           13         0       3   
14           14         0       3   
15           15         0       3   
16           16         1       2   
17           17         0       3   
18           18         1       2   
19           19         0       3   
20           20         1       3   

                                                 Name     Sex        Age  \
1                             Braund, Mr. Owen Harris    male  22.000000   
2   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.000000   
3                              Heikkinen, Miss. Laina  female  26.000000   
4        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.000000   
5                            Allen, Mr. William Henry    male  35.000000   
6                                    Moran, Mr. James    male  29.699118   
7                             McCarthy, Mr. Timothy J    male  54.000000   
8                      Palsson, Master. Gosta Leonard    male   2.000000   
9   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.000000   
10                Nasser, Mrs. Nicholas (Adele Achem)  female  14.000000   
11                    Sandstrom, Miss. Marguerite Rut  female   4.000000   
12                           Bonnell, Miss. Elizabeth  female  58.000000   
13                     Saundercock, Mr. William Henry    male  20.000000   
14                        Andersson, Mr. Anders Johan    male  39.000000   
15               Vestrom, Miss. Hulda Amanda Adolfina  female  14.000000   
16                   Hewlett, Mrs. (Mary D Kingcome)   female  55.000000   
17                               Rice, Master. Eugene    male   2.000000   
18                       Williams, Mr. Charles Eugene    male  29.699118   
19  Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.000000   
20                            Masselmani, Mrs. Fatima  female  29.699118   

    SibSp  Parch            Ticket     Fare Cabin Embarked  Name_len  \
1       1      0         A/5 21171   7.2500  C000        S        23   
2       1      0          PC 17599  71.2833   C85        C        51   
3       0      0  STON/O2. 3101282   7.9250  C000        S        22   
4       1      0            113803  53.1000  C123        S        44   
5       0      0            373450   8.0500  C000        S        24   
6       0      0            330877   8.4583  C000        Q        16   
7       0      0             17463  51.8625   E46        S        23   
8       3      1            349909  21.0750  C000        S        30   
9       0      2            347742  11.1333  C000        S        49   
10      1      0            237736  30.0708  C000        C        35   
11      1      1           PP 9549  16.7000    G6        S        31   
12      0      0            113783  26.5500  C103        S        24   
13      0      0         A/5. 2151   8.0500  C000        S        30   
14      1      5            347082  31.2750  C000        S        27   
15      0      0            350406   7.8542  C000        S        36   
16      0      0            248706  16.0000  C000        S        32   
17      4      1            382652  29.1250  C000        Q        20   
18      0      0            244373  13.0000  C000        S        28   
19      1      0            345763  18.0000  C000        S        55   
20      0      0              2649   7.2250  C000        C        23   

   Child_Adult  
1        Young  
2        Adult  
3        Adult  
4        Adult  
5        Adult  
6        Adult